obj-$(CONFIG_SPM)  	   			+= spm.o
obj-$(CONFIG_SPM_AGC)  			+= agc/
obj-$(CONFIG_SPM_BOTTOM)  		+= bottom/
obj-$(CONFIG_SPM_SOURCE_CHIP)  	+= spm_chip/
obj-$(CONFIG_SPM_SOURCE_FPGA)  	+= spm_fpga/
obj-$(CONFIG_SPM_SOURCE_X86)  	+= spm_x86/